name: Ingest 2019-nCov/SARS-CoV-2 data from GISAID for nextstrain.org/ncov

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - source-data/gisaid_annotations.tsv

  # Manually triggered using `./bin/trigger ingest`
  repository_dispatch:
    types: ingest

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install pipenv
        pipenv sync
        pipenv run ./bin/ingest-gisaid
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ncov-gisaid-updates
